version: "3"
services:
  app:
    image: docker_spring:${TAG}
    volumes:
      - /private/logs_blue:/logs
    deploy:
      replicas: 2
      restart_policy:
        condition: none
    ports:
      - 8082:8081
    networks:
      - frontend
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8081"]
     interval: 30s
     timeout: 5s
     retries: 3
networks:
  frontend:

