version: "3"
services:
  app:
    image: docker_spring:${TAG}
    volumes:
      - /private/logs_green:/logs
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - 8083:8081
    networks:
      - frontend
networks:
  frontend:

