version: "3"
services:
  app:
    image: docker_spring:${TAG}
    volumes:
      - /private/logs_blue:/logs
    deploy:
      replicas: 2
      restart_policy:
        condition: none
    ports:
      - 8082:8081
    networks:
      - frontend
networks:
  frontend:

