version: "3"
services:
  app:
    image: test
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - 8082:8081
    networks:
      - frontend
networks:
  frontend:

