version: "3"
volumes:
  app_logs: {}
services:
  app:
    image: docker_spring:${TAG}
    volumes:
      - app_logs:/logs
    deploy:
      replicas: 2
      restart_policy:
        condition: none
    ports:
      - 8083:8081
    networks:
      - frontend
networks:
  frontend:

