# default: 공통Common 적용
info:
  app:
    encoding: \${file.encoding}
    java.source: \${java.version}
    java.target: \${java.version}
logging:
  file: logs/application-debug.log
  level:
    kakaopay.com.boot.springboot: DEBUG
server:
  port: 8081
# ExampleProperties
example:
  remote-address: 192.168.1.1
  security:
    username: admin
    roles:
      - USER
      - ADMIN
spring:
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    beans:
      cache:
        time-to-live: 10s
    shutdown:
      enabled: true
    health:
      show-details: never
    httptrace:
      enabled: true

